### ISSUE TITLE
Crawler cannot get photo URL

### ISSUE THREAD

**Issue by tad0616** [lefuturiste/google-photos-album-crawler#1]
Hello.
I really like this program, it is very useful and works very well.
However, it seems that the syntax of Google photos has changed recently, so that the regular expression cannot get the photo URL.
We need your help. Thank you very much.

**Comment by lefuturiste** [comment]
Should be fixed with 2a970a15f744bade170e99fa38e58b108e68a164
This is a common issue when building crawler you have to continuously update the code  :)

**Comment by lefuturiste** [comment]
Should be fixed with [v1.1](https://github.com/lefuturiste/google-photos-album-crawler/releases/tag/v1.1) available on composer

**Comment by tad0616** [comment]
You're amazing!
The program is working perfectly!
Thank you very much!

**Comment by lefuturiste** [comment]
Thanks for the feedback I'm glad that you enjoyed!
