### ISSUE TITLE
Google has changed the syntax of its photo albums again, and it needs your help!

### ISSUE THREAD

**Issue by tad0616** [lefuturiste/google-photos-album-crawler#2]
Hello.
Thanks for your help last time, it was working fine until the day before yesterday, when Google changed the syntax of the album.
So, could you please take a look at it again when you have time, thank you very much.

**Comment by tad0616** [comment]
I've found a solution.
At the end of $json there is an extra ", sideChannel: {}"
Just remove it and it will work fine.

**Comment by lefuturiste** [comment]
So I just need to replace the $json line?
`$json = str_replace(', sideChannel: {}', '', $matches[0][1]);`
